# Minimal theme config
theme: jekyll-theme-minimal

title: Arav Chauhan
logo: /assets/img/IMG_1394.JPG
description: MSc Data Science and Analytics @ University of Leeds. Specialising in ML, DL, and LLM/RAG systems.

# Social links (shows in sidebar) 
github_username: Arav810
linkedin_username: https://www.linkedin.com/in/arav-chauhan-453164266
show_downloads: false
